"use client";
import { FormEvent, useState } from "react"; import { ArrowUpRight, WhatsAppIcon } from "@/components/ui/icons";
const interests = ["Corporate gift boxes", "Employee onboarding kits", "Drinkware", "Technology accessories", "Apparel & uniforms", "Notebooks & stationery", "Event merchandise", "Custom packaging", "Something else"];
export function EnquiryForm() { const [errors, setErrors] = useState<Record<string,string>>({}); const err = (n:string) => errors[n] ? <span className="field-error" id={`${n}-error`}>{errors[n]}</span> : null; const a11y = (n:string) => ({ "aria-invalid": !!errors[n], "aria-describedby": errors[n] ? `${n}-error` : undefined });
  function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); const f=e.currentTarget,d=new FormData(f), required=["name","company","phone","interest","quantity","city","details"], next:Record<string,string>={}; required.forEach(n=>{if(!String(d.get(n)||"").trim())next[n]="Please complete this field."}); const email=String(d.get("email")||"").trim(); if(email&&!/^\S+@\S+\.\S+$/.test(email))next.email="Please enter a valid email address."; setErrors(next); if(Object.keys(next).length){setTimeout(()=>f.querySelector<HTMLElement>("[aria-invalid='true']")?.focus());return;} const msg=["Hello Future Signing, I would like to discuss a project.","",`Name: ${d.get("name")}`,`Company: ${d.get("company")}`,`Phone / WhatsApp: ${d.get("phone")}`,`Email: ${d.get("email")||"Not provided"}`,`Product interest: ${d.get("interest")}`,`Estimated quantity: ${d.get("quantity")}`,`Delivery city: ${d.get("city")}`,`Expected deadline: ${d.get("deadline")||"To be discussed"}`,`Project details: ${d.get("details")}`].join("\n"); window.open(`https://wa.me/923001234567?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer"); }
  return <form className="enquiry-form" onSubmit={submit} noValidate><div className="form-grid">
    <label><span>Name *</span><input name="name" autoComplete="name" placeholder="Your name" {...a11y("name")} />{err("name")}</label><label><span>Company *</span><input name="company" autoComplete="organization" placeholder="Company name" {...a11y("company")} />{err("company")}</label>
    <label><span>Phone / WhatsApp *</span><input name="phone" type="tel" autoComplete="tel" placeholder="+92" {...a11y("phone")} />{err("phone")}</label><label><span>Email</span><input name="email" type="email" autoComplete="email" placeholder="name@company.com" {...a11y("email")} />{err("email")}</label>
    <label><span>Product interest *</span><select name="interest" defaultValue="" {...a11y("interest")}><option value="" disabled>Select a category</option>{interests.map(x=><option key={x}>{x}</option>)}</select>{err("interest")}</label><label><span>Estimated quantity *</span><input name="quantity" inputMode="numeric" placeholder="e.g. 250 units" {...a11y("quantity")} />{err("quantity")}</label>
    <label><span>Delivery city *</span><input name="city" autoComplete="address-level2" placeholder="e.g. Lahore" {...a11y("city")} />{err("city")}</label><label><span>Expected deadline</span><input name="deadline" type="date" /></label>
    <label className="wide"><span>Project details *</span><textarea name="details" rows={4} placeholder="Tell us about the occasion, products, branding and budget range." {...a11y("details")} />{err("details")}</label></div><div className="form-submit"><p>Your details are used only to prepare your WhatsApp enquiry.</p><button className="button button--orange" type="submit"><WhatsAppIcon /> Send via WhatsApp <ArrowUpRight /></button></div></form>;
}
